name: Build Executables

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-release:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            file: server.exe
            target: node22-win-x64
            file-name: TS3-ChineseWebPageManager-win-x64-${{ github.event.release.tag_name }}.exe
          - os: ubuntu-latest
            file: server
            target: node22-linux-x64
            file-name: ts3-manager-linux-x64-${{ github.event.release.tag_name }}
          - os: macos-latest
            file: server
            target: node22-macos-x64
            file-name: ts3-manager-macos-x64-${{ github.event.release.tag_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build management page
        run: npm run ui:build

      - name: Build executable
        run: npm exec --workspace=@ts3-manager/server -- pkg . --target ${{ matrix.target }}

      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/server/${{ matrix.file }}
          asset_name: ${{ matrix.file-name }}
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
